# Queries and Mutation

type Query {
	allUser: [User]
	getUser(userCredentials: getUserData): User
	allRooms: [Room]
	getRoomData(roomCredentials: getRoomData): Room
}

type Mutation {
	registerUser(user: registerUser): User
	createRoom(room: roomInput): Room
}
