type Room {
	id: ID!
	roomName: String!
	roomId: String!
	users: [String]!
	admins: [String]!
	blockedUser: [String]
	message: String
}

input roomInput {
	roomName: String!
	roomId: String!
	users: [String]!
	admins: [String]!
	blockedUser: [String]
}
