type Room {
	id: ID!
	roomName: String!
	roomId: String!
	users: [String]!
	admins: [String]!
	blockedUser: [String]
	chats: [String]
	message: String
}

type sendTextResult {
	userName: String!
	userId: String!
	text: String!
	time: String!
	message: String
}

input roomInput {
	roomName: String!
	roomId: String!
	users: [String]!
	admins: [String]!
	blockedUser: [String]
}

input getRoomData {
	roomIds: [String]!
	userId: String!
}

input joinRoomInput {
	userId: String!
	queryKey: String!
	roomId: String!
}

input textBodyInput {
	roomId: String!
	userName: String!
	userId: String!
	queryKey: String!
	text: String!
	time: String!
}
